package JavaApp;

import java.util.ArrayList;


/**
 * 初期リンクを追加するための専用クラス
 */
public class InitialLinkAdder {

    public static void addInitialLinks(SemanticNet semanticNet) {
        ArrayList<Link> initialLinks = new ArrayList<>();
        initialLinks.add(new Link("supplement", "一休", "【東証一部上場】～日本最大級のレストラン予約サイト～", semanticNet));
        initialLinks.add(new Link("URL", "一休", "https://hackathon-x33o.onrender.com/JavaApp/Ikkyu", semanticNet));
        initialLinks.add(new Link("employeeCount", "一休", "100～300人未満", semanticNet));
        initialLinks.add(new Link("averageSalary", "一休", "1000万円～1200万円", semanticNet));
        initialLinks.add(new Link("is-a", "一休", "旅行・ホテル", semanticNet));
        initialLinks.add(new Link("locate", "一休", "東京", semanticNet));
        initialLinks.add(new Link("picturePath", "一休", "/ikkyu.png", semanticNet));
        initialLinks.add(new Link("picturePath", "Sony", "/Sony.jpg", semanticNet));
        initialLinks.add(new Link("averageSalary", "Fujitsu", "800万円～900万円", semanticNet));
        initialLinks.add(new Link("employeeCount", "Fujitsu", "10万人～15万人未満", semanticNet));

        initialLinks.add(new Link("averageSalary", "NEC", "700万円～800万円", semanticNet));
        initialLinks.add(new Link("employeeCount", "NEC", "10万人～15万人未満", semanticNet));

        initialLinks.add(new Link("averageSalary", "NTT-Data", "800万円～900万円", semanticNet));
        initialLinks.add(new Link("employeeCount", "NTT-Data", "10万人～15万人未満", semanticNet));

        initialLinks.add(new Link("averageSalary", "Rakuten", "800万円～900万円", semanticNet));
        initialLinks.add(new Link("employeeCount", "Rakuten", "1万人～3万人未満", semanticNet));

        initialLinks.add(new Link("averageSalary", "Mercari", "600万円～700万円", semanticNet));
        initialLinks.add(new Link("employeeCount", "Mercari", "1000人～3000人未満", semanticNet));

        initialLinks.add(new Link("averageSalary", "Yahoo-Japan", "700万円～800万円", semanticNet));
        initialLinks.add(new Link("employeeCount", "Yahoo-Japan", "1万人～3万人未満", semanticNet));

        initialLinks.add(new Link("averageSalary", "LINE", "700万円～800万円", semanticNet));
        initialLinks.add(new Link("employeeCount", "LINE", "1万人～3万人未満", semanticNet));

        initialLinks.add(new Link("averageSalary", "SoftBank", "900万円～1000万円", semanticNet));
        initialLinks.add(new Link("employeeCount", "SoftBank", "1万人～3万人未満", semanticNet));

        initialLinks.add(new Link("averageSalary", "NTT-Communications", "900万円～1000万円", semanticNet));
        initialLinks.add(new Link("employeeCount", "NTT-Communications", "3000人～5000人未満", semanticNet));

        initialLinks.add(new Link("averageSalary", "KDDI", "900万円～1000万円", semanticNet));
        initialLinks.add(new Link("employeeCount", "KDDI", "3万人～5万人未満", semanticNet));

        initialLinks.add(new Link("averageSalary", "Sony", "1000万円～1200万円", semanticNet));
        initialLinks.add(new Link("employeeCount", "Sony", "10万人～15万人未満", semanticNet));

        initialLinks.add(new Link("averageSalary", "Panasonic", "700万円～800万円", semanticNet));
        initialLinks.add(new Link("employeeCount", "Panasonic", "20万人～25万人未満", semanticNet));

        initialLinks.add(new Link("averageSalary", "Canon", "800万円～900万円", semanticNet));
        initialLinks.add(new Link("employeeCount", "Canon", "15万人～20万人未満", semanticNet));

        initialLinks.add(new Link("averageSalary", "Trend-Micro", "800万円～900万円", semanticNet));
        initialLinks.add(new Link("employeeCount", "Trend-Micro", "1万人～3万人未満", semanticNet));

        initialLinks.add(new Link("averageSalary", "CyberAgent", "700万円～800万円", semanticNet));
        initialLinks.add(new Link("employeeCount", "CyberAgent", "3000人～5000人未満", semanticNet));

        initialLinks.add(new Link("averageSalary", "GMO-Internet", "700万円～800万円", semanticNet));
        initialLinks.add(new Link("employeeCount", "GMO-Internet", "1万人～3万人未満", semanticNet));

        initialLinks.add(new Link("is-a", "Fujitsu", "システムインテグレーター", semanticNet));
        initialLinks.add(new Link("is-a", "NEC", "システムインテグレーター", semanticNet));
        initialLinks.add(new Link("is-a", "NTT-Data", "システムインテグレーター", semanticNet));
        initialLinks.add(new Link("is-a", "Rakuten", "電子商取引", semanticNet));
        initialLinks.add(new Link("is-a", "Mercari", "電子商取引", semanticNet));
        initialLinks.add(new Link("is-a", "Yahoo-Japan", "インターネットサービス", semanticNet));
        initialLinks.add(new Link("is-a", "LINE", "ソーシャルネットワーキング", semanticNet));
        initialLinks.add(new Link("is-a", "SoftBank", "通信", semanticNet));
        initialLinks.add(new Link("is-a", "NTT-Communications", "通信", semanticNet));
        initialLinks.add(new Link("is-a", "KDDI", "通信", semanticNet));
        initialLinks.add(new Link("is-a", "Sony", "電子機器", semanticNet));
        initialLinks.add(new Link("is-a", "Panasonic", "電子機器", semanticNet));
        initialLinks.add(new Link("is-a", "Canon", "電子機器", semanticNet));
        initialLinks.add(new Link("is-a", "Trend-Micro", "サイバーセキュリティ", semanticNet));
        initialLinks.add(new Link("is-a", "CyberAgent", "デジタルマーケティング", semanticNet));
        initialLinks.add(new Link("is-a", "GMO-Internet", "インターネットサービス", semanticNet));

        initialLinks.add(new Link("locate", "Fujitsu", "東京", semanticNet));
        initialLinks.add(new Link("locate", "NEC", "東京", semanticNet));
        initialLinks.add(new Link("locate", "NTT-Data", "東京", semanticNet));
        initialLinks.add(new Link("locate", "Rakuten", "東京", semanticNet));
        initialLinks.add(new Link("locate", "Mercari", "東京", semanticNet));
        initialLinks.add(new Link("locate", "Yahoo-Japan", "東京", semanticNet));
        initialLinks.add(new Link("locate", "LINE", "東京", semanticNet));
        initialLinks.add(new Link("locate", "SoftBank", "東京", semanticNet));
        initialLinks.add(new Link("locate", "NTT-Communications", "東京", semanticNet));
        initialLinks.add(new Link("locate", "KDDI", "東京", semanticNet));
        initialLinks.add(new Link("locate", "Sony", "東京", semanticNet));
        initialLinks.add(new Link("locate", "Panasonic", "大阪", semanticNet));
        initialLinks.add(new Link("locate", "Canon", "東京", semanticNet));
        initialLinks.add(new Link("locate", "Trend-Micro", "東京", semanticNet));
        initialLinks.add(new Link("locate", "CyberAgent", "東京", semanticNet));
        initialLinks.add(new Link("locate", "GMO-Internet", "東京", semanticNet));
        initialLinks.add(new Link("URL", "Fujitsu", "https://www.fujitsu.com/", semanticNet));
        initialLinks.add(new Link("URL", "NEC", "https://www.nec.com/", semanticNet));
        initialLinks.add(new Link("URL", "NTT-Data", "https://www.nttdata.com/", semanticNet));
        initialLinks.add(new Link("URL", "Rakuten", "https://www.rakuten.com/", semanticNet));
        initialLinks.add(new Link("URL", "Mercari", "https://www.mercari.com/", semanticNet));
        initialLinks.add(new Link("URL", "Yahoo-Japan", "https://www.yahoo.co.jp/", semanticNet));
        initialLinks.add(new Link("URL", "LINE", "https://line.me/", semanticNet));
        initialLinks.add(new Link("URL", "SoftBank", "https://www.softbank.jp/", semanticNet));
        initialLinks.add(new Link("URL", "NTT-Communications", "https://www.ntt.com/", semanticNet));
        initialLinks.add(new Link("URL", "KDDI", "https://www.kddi.com/", semanticNet));
        initialLinks.add(new Link("URL", "Sony", "https://www.sony.com/", semanticNet));
        initialLinks.add(new Link("URL", "Panasonic", "https://www.panasonic.com/", semanticNet));
        initialLinks.add(new Link("URL", "Canon", "https://global.canon/", semanticNet));
        initialLinks.add(new Link("URL", "Trend-Micro", "https://www.trendmicro.com/", semanticNet));
        initialLinks.add(new Link("URL", "CyberAgent", "https://www.cyberagent.co.jp/", semanticNet));
        initialLinks.add(new Link("URL", "GMO-Internet", "https://www.gmo.jp/", semanticNet));
        initialLinks.add(new Link("supplement", "Fujitsu", "富士通株式会社（ふじつう、英: Fujitsu Limited）は、神奈川県川崎市中原区に本社を置く日本の総合電機メーカー兼総合ITベンダー。通信システム、情報処理システムおよび電子デバイスの製造・販売ならびにそれらに関するサービスの提供を行っている。", semanticNet));
        initialLinks.add(new Link("supplement", "NEC", "日本電気株式会社（にほんでんき、英: NEC Corporation）は、東京都港区に本社を置く日本の電機メーカー。ITサービス、通信機器、セキュリティソリューションなど多岐にわたる事業を展開し、特にICT分野で国内外でのプレゼンスを誇る。", semanticNet));
        initialLinks.add(new Link("supplement", "NTT-Data", "株式会社エヌ・ティ・ティ・データ（NTT DATA Corporation）は、東京都江東区に本社を置く、情報システムの開発・運用を主な事業とする日本のITサービス企業。NTTグループの一員であり、国内最大級のITサービスプロバイダー。", semanticNet));
        initialLinks.add(new Link("supplement", "Rakuten", "楽天グループ株式会社（らくてん、英: Rakuten Group, Inc.）は、東京都世田谷区に本社を置く、日本を代表するECサイト運営や金融サービスを展開する企業。ECサイト「楽天市場」を中心に、幅広いオンラインサービスを提供している。", semanticNet));
        initialLinks.add(new Link("supplement", "Mercari", "株式会社メルカリ（Mercari, Inc.）は、東京都港区に本社を置く日本のIT企業。フリマアプリ「メルカリ」の運営を行い、国内外でのサービス展開を行っている。", semanticNet));
        initialLinks.add(new Link("supplement", "Yahoo-Japan", "Zホールディングス株式会社（旧称: Yahoo Japan Corporation）は、東京都千代田区に本社を置く日本のIT企業。検索エンジンやオンラインショッピング、広告事業を展開するインターネット関連企業。", semanticNet));
        initialLinks.add(new Link("supplement", "LINE", "LINE株式会社は、東京都新宿区に本社を置く日本のIT企業。無料メッセージアプリ「LINE」を中心に、広告、フィンテック、エンターテインメント事業を展開。", semanticNet));
        initialLinks.add(new Link("supplement", "SoftBank", "ソフトバンク株式会社（SoftBank Corp.）は、東京都港区に本社を置く日本の通信事業者。モバイル通信事業を中心に、インターネットサービスやIoT分野での事業も展開。", semanticNet));
        initialLinks.add(new Link("supplement", "NTT-Communications", "エヌ・ティ・ティ・コミュニケーションズ株式会社（NTT Communications Corporation）は、東京都千代田区に本社を置く、日本の通信事業会社。国際通信やクラウドサービスを中心とした事業を行っている。", semanticNet));
        initialLinks.add(new Link("supplement", "KDDI", "KDDI株式会社（ケイディーディーアイ、英: KDDI Corporation）は、東京都千代田区に本社を置く日本の通信事業者。auブランドで知られるモバイル通信を中心に、固定通信やIoT事業も展開している。", semanticNet));
        initialLinks.add(new Link("supplement", "Sony", "ソニーグループ株式会社（Sony Group Corporation）は、東京都港区に本社を置く日本の多国籍コングロマリット。家電、音楽、映画、ゲームなど多岐にわたる分野で世界的なプレゼンスを持つ。", semanticNet));
        initialLinks.add(new Link("supplement", "Panasonic", "パナソニック株式会社（Panasonic Corporation）は、大阪府門真市に本社を置く日本の総合電機メーカー。家電、住宅設備、エコソリューションなどの多様な事業を展開している。", semanticNet));
        initialLinks.add(new Link("supplement", "Canon", "キヤノン株式会社（Canon Inc.）は、東京都大田区に本社を置く日本の電機メーカー。カメラ、プリンター、医療機器などを中心に幅広い分野で事業を展開。", semanticNet));
        initialLinks.add(new Link("supplement", "Trend-Micro", "トレンドマイクロ株式会社（Trend Micro Incorporated）は、東京都渋谷区に本社を置く日本のITセキュリティ企業。ウイルス対策ソフトウェアやセキュリティソリューションを提供。", semanticNet));
        initialLinks.add(new Link("supplement", "CyberAgent", "株式会社サイバーエージェント（CyberAgent, Inc.）は、東京都渋谷区に本社を置く日本のIT企業。広告事業、ゲーム、メディア運営を中心に事業を展開。", semanticNet));
        initialLinks.add(new Link("supplement", "GMO-Internet", "GMOインターネット株式会社（GMO Internet Group, Inc.）は、東京都渋谷区に本社を置く日本のIT企業。ドメイン登録、ホスティング、インターネット広告事業を展開。", semanticNet));
        initialLinks.add(new Link("picturePath", "Fujitsu", "/Fujitsu.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "NEC", "/NEC.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "NTT-Data", "/NTT-Data.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "Rakuten", "/Rakuten.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "Mercari", "/Mercari.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "Yahoo-Japan", "/Yahoo-Japan.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "LINE", "/LINE.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "SoftBank", "/SoftBank.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "NTT-Communications", "/NTT-Communications.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "KDDI", "/KDDI.jpg", semanticNet));

        initialLinks.add(new Link("picturePath", "Panasonic", "/Panasonic.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "Canon", "/Canon.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "Trend-Micro", "/Trend-Micro.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "CyberAgent", "/CyberAgent.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "GMO-Internet", "/GMO-Internet.jpg", semanticNet));

        initialLinks.add(new Link("is-a", "スターツグループPICK UP", "不動産", semanticNet));
        initialLinks.add(new Link("is-a", "(株)オービックPICK UP", "情報処理", semanticNet));
        initialLinks.add(new Link("is-a", "(株)ミスターマックス・ホールディングス【東証プライム市場上場】", "スーパーマーケット", semanticNet));
        initialLinks.add(new Link("is-a", "オムロングループ", "半導体・電子・電気機器", semanticNet));
        initialLinks.add(new Link("is-a", "MHI　NSエンジニアリング(株)（三菱重工グループ）", "機械設計", semanticNet));
        initialLinks.add(new Link("is-a", "CTCテクノロジー(株)【CTCT／CTCグループ】", "情報処理", semanticNet));
        initialLinks.add(new Link("is-a", "(株)ライターム", "ソフトウエア", semanticNet));
        initialLinks.add(new Link("is-a", "(株)ワイズ", "商社（電子・電気機器・OA機器）", semanticNet));
        initialLinks.add(new Link("is-a", "(株)ボードルア【東証グロース上場】", "情報処理", semanticNet));
        initialLinks.add(new Link("is-a", "ラディックス(株)", "商社（文具・事務用品・日用品）", semanticNet));
        initialLinks.add(new Link("is-a", "日鉄ソリューションズ中部(株)【旧社名：(株)NSソリューションズ中部】", "情報処理", semanticNet));
        initialLinks.add(new Link("is-a", "(株)アスパーク", "機械設計", semanticNet));
        initialLinks.add(new Link("is-a", "(株)北電子", "ゲーム・玩具・アミューズメント製品", semanticNet));
        initialLinks.add(new Link("is-a", "JFEシステムズ(株)【東証スタンダード市場上場】", "情報処理", semanticNet));
        initialLinks.add(new Link("is-a", "NRIネットコム(株)【野村総合研究所(NRI)グループ】", "ソフトウエア", semanticNet));
        initialLinks.add(new Link("is-a", "エス・ビー・システムズ(株)【CGCグループ】", "情報処理", semanticNet));
        initialLinks.add(new Link("is-a", "(株)トップ【総合医療機器メーカー】", "医療用機器・医療関連", semanticNet));
        initialLinks.add(new Link("is-a", "デンソーテクノ(株)", "ソフトウエア", semanticNet));
        initialLinks.add(new Link("is-a", "(株)システムインテグレータ【東証スタンダード上場】", "ソフトウエア", semanticNet));
        initialLinks.add(new Link("is-a", "(株)CLIS", "情報処理", semanticNet));
        initialLinks.add(new Link("is-a", "(株)コプロ・ホールディングス（東証プライム・名証プレミア上場）他2社", "人材派遣・人材紹介", semanticNet));
        initialLinks.add(new Link("is-a", "ウェルネスダイニング(株)", "食品", semanticNet));
        initialLinks.add(new Link("is-a", "サティス(株)", "情報処理", semanticNet));
        initialLinks.add(new Link("is-a", "萩原電気ホールディングス(株)【東証プライム上場】", "商社（電子・電気機器・OA機器）", semanticNet));
        initialLinks.add(new Link("is-a", "(株)ランディックス【東証グロース上場】", "不動産", semanticNet));
        initialLinks.add(new Link("is-a", "ロジスティードソリューションズ(株)", "ソフトウエア", semanticNet));
        initialLinks.add(new Link("is-a", "エイチ・シー・ネットワークス(株)", "情報処理", semanticNet));
        initialLinks.add(new Link("is-a", "オリエントブレイン(株)", "精密機器", semanticNet));
        initialLinks.add(new Link("is-a", "(株)ワンエイティ", "広告", semanticNet));
        initialLinks.add(new Link("is-a", "あいおいニッセイ同和損害保険(株)", "損害保険", semanticNet));
        initialLinks.add(new Link("is-a", "日本軽金属(株)", "非鉄金属", semanticNet));
        initialLinks.add(new Link("is-a", "日本コムシス(株)", "設備工事・設備設計", semanticNet));
        initialLinks.add(new Link("is-a", "(株)野村総合研究所", "情報処理", semanticNet));
        initialLinks.add(new Link("is-a", "(株)NTTデータNJK", "ソフトウエア", semanticNet));
        initialLinks.add(new Link("is-a", "都築電気(株)【東証プライム市場上場】", "情報処理", semanticNet));
        initialLinks.add(new Link("is-a", "兼松エレクトロニクス(株)", "情報処理", semanticNet));
        initialLinks.add(new Link("is-a", "(株)リンクレア", "情報処理", semanticNet));
        initialLinks.add(new Link("is-a", "(株)TKC【東証プライム市場上場】", "情報処理", semanticNet));
        initialLinks.add(new Link("is-a", "(株)東証コンピュータシステム【富士ソフトグループ】", "インターネット関連", semanticNet));
        initialLinks.add(new Link("is-a", "野村ビジネスサービス(株)【野村グループ】", "各種ビジネスサービス・BPO", semanticNet));
        initialLinks.add(new Link("is-a", "ダイハツ工業(株)", "自動車・自動車部品", semanticNet));
        initialLinks.add(new Link("is-a", "ソニーグローバルソリューションズ(株)", "情報処理", semanticNet));
        initialLinks.add(new Link("is-a", "(株)構造計画研究所", "専門コンサルティング", semanticNet));
        initialLinks.add(new Link("is-a", "理化工業(株)", "精密機器", semanticNet));
        initialLinks.add(new Link("is-a", "ローツェ(株)【東証プライム市場上場】", "機械", semanticNet));
        initialLinks.add(new Link("is-a", "トラスコ中山(株)【東証プライム市場上場】", "商社（機械・プラント・環境）", semanticNet));
        initialLinks.add(new Link("is-a", "(株)フォーバル【東証スタンダード上場】", "専門コンサルティング", semanticNet));
        initialLinks.add(new Link("is-a", "三谷商事(株)", "商社（複合）", semanticNet));
        initialLinks.add(new Link("is-a", "ケミカルグラウト(株)【鹿島グループ】", "建設", semanticNet));
        initialLinks.add(new Link("is-a", "(株)電通総研【旧社名：(株)電通国際情報サービス（ISID）】", "情報処理", semanticNet));
        initialLinks.add(new Link("is-a", "横河ブリッジホールディングスグループ", "建設", semanticNet));
        initialLinks.add(new Link("is-a", "(株)前田製作所", "機械", semanticNet));
        initialLinks.add(new Link("is-a", "日鉄日立システムソリューションズ(株)", "情報処理", semanticNet));
        initialLinks.add(new Link("is-a", "(株)東洋経済新報社", "出版", semanticNet));
        initialLinks.add(new Link("is-a", "豊田通商システムズ(株)(豊田通商グループ)", "情報処理", semanticNet));
        initialLinks.add(new Link("is-a", "(株)インテリジェント ウェイブ【東証プライム市場上場】", "情報処理", semanticNet));
        initialLinks.add(new Link("is-a", "アサヒビジネスソリューションズ", "情報処理", semanticNet));
        initialLinks.add(new Link("is-a", "(株)トラストシステム（ミライトワングループ）", "ソフトウエア", semanticNet));
        initialLinks.add(new Link("is-a", "(株)フェローズ", "人材派遣・人材紹介", semanticNet));
        initialLinks.add(new Link("is-a", "サンワコムシスエンジニアリング(株)【コムシスグループ】", "設備工事・設備設計", semanticNet));
        initialLinks.add(new Link("is-a", "デル・テクノロジーズ(株)", "情報処理", semanticNet));
        initialLinks.add(new Link("is-a", "日本テクノストラクチャア(株)", "ソフトウエア", semanticNet));
        initialLinks.add(new Link("is-a", "SOMPOダイレクト損害保険(株)", "損害保険", semanticNet));
        initialLinks.add(new Link("is-a", "JFEプラントエンジ(株)", "プラント・エンジニアリング", semanticNet));
        initialLinks.add(new Link("is-a", "(株)All Ads", "広告", semanticNet));
        initialLinks.add(new Link("is-a", "(株)エクシオテック", "設備工事・設備設計", semanticNet));
        initialLinks.add(new Link("is-a", "(株)テクノプロジェクト", "ソフトウエア", semanticNet));
        initialLinks.add(new Link("is-a", "(株)JSOL（ジェイソル）", "情報処理", semanticNet));
        initialLinks.add(new Link("is-a", "中電技術コンサルタント(株)【中国電力グループ】", "建設コンサルタント", semanticNet));
        initialLinks.add(new Link("is-a", "(株)ゼウス・エンタープライズ", "情報処理", semanticNet));
        initialLinks.add(new Link("is-a", "光村図書出版(株)", "出版", semanticNet));
        initialLinks.add(new Link("is-a", "(株)テー・オー・ダブリュー", "広告", semanticNet));
        initialLinks.add(new Link("is-a", "(株)日経BP", "出版", semanticNet));
        initialLinks.add(new Link("is-a", "(株)プライムクロス【野村不動産グループ】", "広告", semanticNet));
        initialLinks.add(new Link("is-a", "PayPay銀行(株)【LINEヤフーグループ】", "銀行（ネットバンク・その他）", semanticNet));
        initialLinks.add(new Link("is-a", "(株)メディックメディア", "出版", semanticNet));
        initialLinks.add(new Link("is-a", "(株)S-FIT", "不動産", semanticNet));
        initialLinks.add(new Link("is-a", "エムオーテックス(株)", "ソフトウエア", semanticNet));
        initialLinks.add(new Link("is-a", "(株)テレビ朝日サービス", "商社（通信）", semanticNet));
        initialLinks.add(new Link("is-a", "(株)荒谷建設コンサルタント", "建設コンサルタント", semanticNet));
        initialLinks.add(new Link("is-a", "(株)立花エレテック【東証プライム上場】", "商社（電子・電気機器・OA機器）", semanticNet));
        initialLinks.add(new Link("is-a", "(株)ゲームフリーク", "ゲームソフト", semanticNet));
        initialLinks.add(new Link("is-a", "(株)Take Action", "専門コンサルティング", semanticNet));
        initialLinks.add(new Link("is-a", "(株)C-mind", "商社（電子・電気機器・OA機器）", semanticNet));
        initialLinks.add(new Link("is-a", "(株)アール・エム", "インターネット関連", semanticNet));
        initialLinks.add(new Link("is-a", "ビッグローブ(株)", "通信・インフラ", semanticNet));
        initialLinks.add(new Link("is-a", "(株)システムアイ", "情報処理", semanticNet));
        initialLinks.add(new Link("is-a", "(株)ダイテック 【DAITEC Co., Ltd.】", "ソフトウエア", semanticNet));
        initialLinks.add(new Link("is-a", "(株)トップ", "商社（複合）", semanticNet));
        initialLinks.add(new Link("is-a", "(株)SFIDA X", "広告", semanticNet));
        initialLinks.add(new Link("is-a", "SBペイメントサービス(株)（ソフトバンクグループ）", "クレジット・信販", semanticNet));
        initialLinks.add(new Link("is-a", "インフィニオン テクノロジーズ ジャパン(株)", "半導体・電子・電気機器", semanticNet));
        initialLinks.add(new Link("is-a", "(株)三栄建設", "建設", semanticNet));
        initialLinks.add(new Link("is-a", "JBCCグループ", "情報処理", semanticNet));
        initialLinks.add(new Link("is-a", "(株)ネクステップ・ソリューションズ", "ソフトウエア", semanticNet));
        initialLinks.add(new Link("is-a", "パナソニックITS(株)", "ソフトウエア", semanticNet));
        initialLinks.add(new Link("is-a", "グッドモーゲージ(株)【SBIネット銀行ローンプラザ】", "その他金融", semanticNet));
        initialLinks.add(new Link("is-a", "(株)クオレガ(Cuolega)", "人材派遣・人材紹介", semanticNet));
        initialLinks.add(new Link("is-a", "(株)エナリス【KDDIグループ】", "専門コンサルティング", semanticNet));
        initialLinks.add(new Link("is-a", "ワークスデザイン(株)", "広告", semanticNet));


        // Locate information

        initialLinks.add(new Link("locate", "スターツグループPICK UP", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)オービックPICK UP", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)ミスターマックス・ホールディングス【東証プライム市場上場】", "福岡", semanticNet));
        initialLinks.add(new Link("locate", "オムロングループ", "東京", semanticNet));
        initialLinks.add(new Link("locate", "MHI　NSエンジニアリング(株)（三菱重工グループ）", "兵庫", semanticNet));
        initialLinks.add(new Link("locate", "CTCテクノロジー(株)【CTCT／CTCグループ】", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)ライターム", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)ワイズ", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)ボードルア【東証グロース上場】", "東京", semanticNet));
        initialLinks.add(new Link("locate", "ラディックス(株)", "東京", semanticNet));
        initialLinks.add(new Link("locate", "日鉄ソリューションズ中部(株)【旧社名：(株)NSソリューションズ中部】", "愛知", semanticNet));
        initialLinks.add(new Link("locate", "(株)アスパーク", "大阪", semanticNet));
        initialLinks.add(new Link("locate", "(株)北電子", "東京", semanticNet));
        initialLinks.add(new Link("locate", "JFEシステムズ(株)【東証スタンダード市場上場】", "東京", semanticNet));
        initialLinks.add(new Link("locate", "NRIネットコム(株)【野村総合研究所(NRI)グループ】", "東京", semanticNet));
        initialLinks.add(new Link("locate", "エス・ビー・システムズ(株)【CGCグループ】", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)トップ【総合医療機器メーカー】", "東京", semanticNet));
        initialLinks.add(new Link("locate", "デンソーテクノ(株)", "愛知", semanticNet));
        initialLinks.add(new Link("locate", "(株)システムインテグレータ【東証スタンダード上場】", "埼玉", semanticNet));
        initialLinks.add(new Link("locate", "(株)CLIS", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)コプロ・ホールディングス（東証プライム・名証プレミア上場）他2社", "愛知", semanticNet));
        initialLinks.add(new Link("locate", "ウェルネスダイニング(株)", "東京", semanticNet));
        initialLinks.add(new Link("locate", "サティス(株)", "東京", semanticNet));
        initialLinks.add(new Link("locate", "萩原電気ホールディングス(株)【東証プライム上場】", "愛知", semanticNet));
        initialLinks.add(new Link("locate", "(株)ランディックス【東証グロース上場】", "東京", semanticNet));
        initialLinks.add(new Link("locate", "ロジスティードソリューションズ(株)", "東京", semanticNet));
        initialLinks.add(new Link("locate", "エイチ・シー・ネットワークス(株)", "東京", semanticNet));
        initialLinks.add(new Link("locate", "オリエントブレイン(株)", "大阪", semanticNet));
        initialLinks.add(new Link("locate", "(株)ワンエイティ", "東京", semanticNet));
        initialLinks.add(new Link("locate", "あいおいニッセイ同和損害保険(株)", "東京", semanticNet));
        initialLinks.add(new Link("locate", "日本軽金属(株)", "東京", semanticNet));
        initialLinks.add(new Link("locate", "日本コムシス(株)", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)野村総合研究所", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)NTTデータNJK", "東京", semanticNet));
        initialLinks.add(new Link("locate", "都築電気(株)【東証プライム市場上場】", "東京", semanticNet));
        initialLinks.add(new Link("locate", "兼松エレクトロニクス(株)", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)リンクレア", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)TKC【東証プライム市場上場】", "栃木", semanticNet));
        initialLinks.add(new Link("locate", "(株)東証コンピュータシステム【富士ソフトグループ】", "東京", semanticNet));
        initialLinks.add(new Link("locate", "野村ビジネスサービス(株)【野村グループ】", "東京", semanticNet));
        initialLinks.add(new Link("locate", "ダイハツ工業(株)", "大阪", semanticNet));
        initialLinks.add(new Link("locate", "ソニーグローバルソリューションズ(株)", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)構造計画研究所", "東京", semanticNet));
        initialLinks.add(new Link("locate", "理化工業(株)", "東京", semanticNet));
        initialLinks.add(new Link("locate", "ローツェ(株)【東証プライム市場上場】", "広島", semanticNet));
        initialLinks.add(new Link("locate", "トラスコ中山(株)【東証プライム市場上場】", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)フォーバル【東証スタンダード上場】", "東京", semanticNet));
        initialLinks.add(new Link("locate", "三谷商事(株)", "東京", semanticNet));
        initialLinks.add(new Link("locate", "ケミカルグラウト(株)【鹿島グループ】", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)電通総研【旧社名：(株)電通国際情報サービス（ISID）】", "東京", semanticNet));
        initialLinks.add(new Link("locate", "横河ブリッジホールディングスグループ", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)前田製作所", "長野", semanticNet));
        initialLinks.add(new Link("locate", "日鉄日立システムソリューションズ(株)", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)東洋経済新報社", "東京", semanticNet));
        initialLinks.add(new Link("locate", "豊田通商システムズ(株)(豊田通商グループ)", "愛知", semanticNet));
        initialLinks.add(new Link("locate", "(株)インテリジェント ウェイブ【東証プライム市場上場】", "東京", semanticNet));
        initialLinks.add(new Link("locate", "アサヒビジネスソリューションズ", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)トラストシステム（ミライトワングループ）", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)フェローズ", "東京", semanticNet));
        initialLinks.add(new Link("locate", "サンワコムシスエンジニアリング(株)【コムシスグループ】", "東京", semanticNet));
        initialLinks.add(new Link("locate", "デル・テクノロジーズ(株)", "東京", semanticNet));
        initialLinks.add(new Link("locate", "日本テクノストラクチャア(株)", "東京", semanticNet));
        initialLinks.add(new Link("locate", "SOMPOダイレクト損害保険(株)", "東京", semanticNet));
        initialLinks.add(new Link("locate", "JFEプラントエンジ(株)", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)All Ads", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)エクシオテック", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)テクノプロジェクト", "島根", semanticNet));
        initialLinks.add(new Link("locate", "(株)JSOL（ジェイソル）", "東京", semanticNet));
        initialLinks.add(new Link("locate", "中電技術コンサルタント(株)【中国電力グループ】", "広島", semanticNet));
        initialLinks.add(new Link("locate", "(株)ゼウス・エンタープライズ", "東京", semanticNet));
        initialLinks.add(new Link("locate", "光村図書出版(株)", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)テー・オー・ダブリュー", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)日経BP", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)プライムクロス【野村不動産グループ】", "東京", semanticNet));
        initialLinks.add(new Link("locate", "PayPay銀行(株)【LINEヤフーグループ】", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)メディックメディア", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)S-FIT", "東京", semanticNet));
        initialLinks.add(new Link("locate", "エムオーテックス(株)", "大阪", semanticNet));
        initialLinks.add(new Link("locate", "(株)テレビ朝日サービス", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)荒谷建設コンサルタント", "広島", semanticNet));
        initialLinks.add(new Link("locate", "(株)立花エレテック【東証プライム上場】", "大阪", semanticNet));
        initialLinks.add(new Link("locate", "(株)ゲームフリーク", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)Take Action", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)C-mind", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)アール・エム", "大阪", semanticNet));
        initialLinks.add(new Link("locate", "ビッグローブ(株)", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)システムアイ", "神奈川", semanticNet));
        initialLinks.add(new Link("locate", "(株)ダイテック 【DAITEC Co., Ltd.】", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)トップ", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)SFIDA X", "東京", semanticNet));
        initialLinks.add(new Link("locate", "SBペイメントサービス(株)（ソフトバンクグループ）", "東京", semanticNet));
        initialLinks.add(new Link("locate", "インフィニオン テクノロジーズ ジャパン(株)", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)三栄建設", "大阪", semanticNet));
        initialLinks.add(new Link("locate", "JBCCグループ", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)ネクステップ・ソリューションズ", "東京", semanticNet));
        initialLinks.add(new Link("locate", "パナソニックITS(株)", "神奈川", semanticNet));
        initialLinks.add(new Link("locate", "グッドモーゲージ(株)【SBIネット銀行ローンプラザ】", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)クオレガ(Cuolega)", "東京", semanticNet));
        initialLinks.add(new Link("locate", "(株)エナリス【KDDIグループ】", "東京", semanticNet));
        initialLinks.add(new Link("locate", "ワークスデザイン(株)", "東京", semanticNet));

        // Averagesalary information
        initialLinks.add(new Link("averageSalary", "スターツグループPICK UP", "400万円～600万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)オービックPICK UP", "500万円～700万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)ミスターマックス・ホールディングス【東証プライム市場上場】", "300万円～500万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "オムロングループ", "400万円～600万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "MHI　NSエンジニアリング(株)（三菱重工グループ）", "500万円～700万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "CTCテクノロジー(株)【CTCT／CTCグループ】", "500万円～700万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)ライターム", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)ワイズ", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)ボードルア【東証グロース上場】", "300万円～500万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "ラディックス(株)", "500万円～700万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "日鉄ソリューションズ中部(株)【旧社名：(株)NSソリューションズ中部】", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)アスパーク", "400万円～600万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)北電子", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "JFEシステムズ(株)【東証スタンダード市場上場】", "500万円～700万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "NRIネットコム(株)【野村総合研究所(NRI)グループ】", "300万円～500万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "エス・ビー・システムズ(株)【CGCグループ】", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)トップ【総合医療機器メーカー】", "300万円～500万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "デンソーテクノ(株)", "400万円～600万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)システムインテグレータ【東証スタンダード上場】", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)CLIS", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)コプロ・ホールディングス（東証プライム・名証プレミア上場）他2社", "400万円～600万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "ウェルネスダイニング(株)", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "サティス(株)", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "萩原電気ホールディングス(株)【東証プライム上場】", "300万円～500万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)ランディックス【東証グロース上場】", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "ロジスティードソリューションズ(株)", "300万円～500万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "エイチ・シー・ネットワークス(株)", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "オリエントブレイン(株)", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)ワンエイティ", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "あいおいニッセイ同和損害保険(株)", "400万円～600万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "日本軽金属(株)", "500万円～700万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "日本コムシス(株)", "500万円～700万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)野村総合研究所", "400万円～600万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)NTTデータNJK", "300万円～500万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "都築電気(株)【東証プライム市場上場】", "500万円～700万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "兼松エレクトロニクス(株)", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)リンクレア", "300万円～500万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)TKC【東証プライム市場上場】", "500万円～700万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)東証コンピュータシステム【富士ソフトグループ】", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "野村ビジネスサービス(株)【野村グループ】", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "ダイハツ工業(株)", "400万円～600万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "ソニーグローバルソリューションズ(株)", "300万円～500万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)構造計画研究所", "300万円～500万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "理化工業(株)", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "ローツェ(株)【東証プライム市場上場】", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "トラスコ中山(株)【東証プライム市場上場】", "400万円～600万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)フォーバル【東証スタンダード上場】", "300万円～500万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "三谷商事(株)", "300万円～500万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "ケミカルグラウト(株)【鹿島グループ】", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)電通総研【旧社名：(株)電通国際情報サービス（ISID）】", "400万円～600万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "横河ブリッジホールディングスグループ", "500万円～700万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)前田製作所", "300万円～500万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "日鉄日立システムソリューションズ(株)", "300万円～500万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)東洋経済新報社", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "豊田通商システムズ(株)(豊田通商グループ)", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)インテリジェント ウェイブ【東証プライム市場上場】", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "アサヒビジネスソリューションズ", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)トラストシステム（ミライトワングループ）", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)フェローズ", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "サンワコムシスエンジニアリング(株)【コムシスグループ】", "300万円～500万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "デル・テクノロジーズ(株)", "400万円～600万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "日本テクノストラクチャア(株)", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "SOMPOダイレクト損害保険(株)", "300万円～500万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "JFEプラントエンジ(株)", "400万円～600万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)All Ads", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)エクシオテック", "300万円～500万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)テクノプロジェクト", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)JSOL（ジェイソル）", "500万円～700万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "中電技術コンサルタント(株)【中国電力グループ】", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)ゼウス・エンタープライズ", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "光村図書出版(株)", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)テー・オー・ダブリュー", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)日経BP", "300万円～500万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)プライムクロス【野村不動産グループ】", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "PayPay銀行(株)【LINEヤフーグループ】", "300万円～500万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)メディックメディア", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)S-FIT", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "エムオーテックス(株)", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)テレビ朝日サービス", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)荒谷建設コンサルタント", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)立花エレテック【東証プライム上場】", "300万円～500万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)ゲームフリーク", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)Take Action", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)C-mind", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)アール・エム", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "ビッグローブ(株)", "300万円～500万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)システムアイ", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)ダイテック 【DAITEC Co., Ltd.】", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)トップ", "500万円～700万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)SFIDA X", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "SBペイメントサービス(株)（ソフトバンクグループ）", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "インフィニオン テクノロジーズ ジャパン(株)", "300万円～500万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)三栄建設", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "JBCCグループ", "500万円～700万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)ネクステップ・ソリューションズ", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "パナソニックITS(株)", "300万円～500万円", semanticNet));
        initialLinks.add(new Link("averageSalary", "グッドモーゲージ(株)【SBIネット銀行ローンプラザ】", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)クオレガ(Cuolega)", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "(株)エナリス【KDDIグループ】", "N/A", semanticNet));
        initialLinks.add(new Link("averageSalary", "ワークスデザイン(株)", "N/A", semanticNet));

        // Employeecount information

        initialLinks.add(new Link("employeeCount", "スターツグループPICK UP", "1万人～3万人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)オービックPICK UP", "1000～3000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)ミスターマックス・ホールディングス【東証プライム市場上場】", "500～1000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "オムロングループ", "1万人～3万人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "MHI　NSエンジニアリング(株)（三菱重工グループ）", "1000～3000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "CTCテクノロジー(株)【CTCT／CTCグループ】", "1000～3000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)ライターム", "100～300人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)ワイズ", "100～300人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)ボードルア【東証グロース上場】", "500～1000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "ラディックス(株)", "1000～3000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "日鉄ソリューションズ中部(株)【旧社名：(株)NSソリューションズ中部】", "100～300人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)アスパーク", "3000～5000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)北電子", "100～300人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "JFEシステムズ(株)【東証スタンダード市場上場】", "1000～3000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "NRIネットコム(株)【野村総合研究所(NRI)グループ】", "500～1000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "エス・ビー・システムズ(株)【CGCグループ】", "50～100人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)トップ【総合医療機器メーカー】", "500～1000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "デンソーテクノ(株)", "3000～5000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)システムインテグレータ【東証スタンダード上場】", "100～300人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)CLIS", "300～500人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)コプロ・ホールディングス（東証プライム・名証プレミア上場）他2社", "3000～5000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "ウェルネスダイニング(株)", "～ 50人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "サティス(株)", "～ 50人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "萩原電気ホールディングス(株)【東証プライム上場】", "500～1000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)ランディックス【東証グロース上場】", "100～300人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "ロジスティードソリューションズ(株)", "500～1000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "エイチ・シー・ネットワークス(株)", "300～500人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "オリエントブレイン(株)", "～ 50人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)ワンエイティ", "～ 50人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "あいおいニッセイ同和損害保険(株)", "1万人～3万人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "日本軽金属(株)", "1000～3000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "日本コムシス(株)", "1000～3000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)野村総合研究所", "1万人～3万人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)NTTデータNJK", "500～1000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "都築電気(株)【東証プライム市場上場】", "1000～3000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "兼松エレクトロニクス(株)", "300～500人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)リンクレア", "500～1000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)TKC【東証プライム市場上場】", "1000～3000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)東証コンピュータシステム【富士ソフトグループ】", "300～500人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "野村ビジネスサービス(株)【野村グループ】", "300～500人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "ダイハツ工業(株)", "1万人～3万人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "ソニーグローバルソリューションズ(株)", "500～1000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)構造計画研究所", "500～1000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "理化工業(株)", "300～500人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "ローツェ(株)【東証プライム市場上場】", "300～500人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "トラスコ中山(株)【東証プライム市場上場】", "3000～5000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)フォーバル【東証スタンダード上場】", "500～1000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "三谷商事(株)", "500～1000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "ケミカルグラウト(株)【鹿島グループ】", "300～500人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)電通総研【旧社名：(株)電通国際情報サービス（ISID）】", "3000～5000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "横河ブリッジホールディングスグループ", "1000～3000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)前田製作所", "500～1000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "日鉄日立システムソリューションズ(株)", "500～1000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)東洋経済新報社", "300～500人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "豊田通商システムズ(株)(豊田通商グループ)", "300～500人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)インテリジェント ウェイブ【東証プライム市場上場】", "300～500人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "アサヒビジネスソリューションズ", "100～300人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)トラストシステム（ミライトワングループ）", "100～300人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)フェローズ", "100～300人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "サンワコムシスエンジニアリング(株)【コムシスグループ】", "500～1000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "デル・テクノロジーズ(株)", "3000～5000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "日本テクノストラクチャア(株)", "100～300人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "SOMPOダイレクト損害保険(株)", "500～1000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "JFEプラントエンジ(株)", "3000～5000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)All Ads", "100～300人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)エクシオテック", "500～1000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)テクノプロジェクト", "100～300人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)JSOL（ジェイソル）", "1000～3000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "中電技術コンサルタント(株)【中国電力グループ】", "300～500人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)ゼウス・エンタープライズ", "300～500人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "光村図書出版(株)", "100～300人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)テー・オー・ダブリュー", "100～300人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)日経BP", "500～1000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)プライムクロス【野村不動産グループ】", "100～300人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "PayPay銀行(株)【LINEヤフーグループ】", "500～1000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)メディックメディア", "100～300人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)S-FIT", "300～500人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "エムオーテックス(株)", "300～500人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)テレビ朝日サービス", "100～300人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)荒谷建設コンサルタント", "300～500人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)立花エレテック【東証プライム上場】", "500～1000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)ゲームフリーク", "100～300人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)Take Action", "50～100人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)C-mind", "100～300人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)アール・エム", "300～500人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "ビッグローブ(株)", "500～1000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)システムアイ", "300～500人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)ダイテック 【DAITEC Co., Ltd.】", "300～500人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)トップ", "1000～3000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)SFIDA X", "100～300人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "SBペイメントサービス(株)（ソフトバンクグループ）", "300～500人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "インフィニオン テクノロジーズ ジャパン(株)", "500～1000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)三栄建設", "100～300人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "JBCCグループ", "1000～3000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)ネクステップ・ソリューションズ", "100～300人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "パナソニックITS(株)", "500～1000人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "グッドモーゲージ(株)【SBIネット銀行ローンプラザ】", "100～300人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)クオレガ(Cuolega)", "100～300人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "(株)エナリス【KDDIグループ】", "100～300人未満", semanticNet));
        initialLinks.add(new Link("employeeCount", "ワークスデザイン(株)", "～ 50人未満", semanticNet));

        // Url information
        initialLinks.add(new Link("URL", "スターツグループPICK UP", "https://example.com/スターツグループPICKUP", semanticNet));
        initialLinks.add(new Link("URL", "(株)オービックPICK UP", "https://example.com/株オービックPICKUP", semanticNet));
        initialLinks.add(new Link("URL", "(株)ミスターマックス・ホールディングス【東証プライム市場上場】", "https://example.com/株ミスターマックス・ホールディングス【東証プライム市場上場】", semanticNet));
        initialLinks.add(new Link("URL", "オムロングループ", "https://example.com/オムロングループ", semanticNet));
        initialLinks.add(new Link("URL", "MHI　NSエンジニアリング(株)（三菱重工グループ）", "https://example.com/MHI　NSエンジニアリング株（三菱重工グループ）", semanticNet));
        initialLinks.add(new Link("URL", "CTCテクノロジー(株)【CTCT／CTCグループ】", "https://example.com/CTCテクノロジー株【CTCT／CTCグループ】", semanticNet));
        initialLinks.add(new Link("URL", "(株)ライターム", "https://example.com/株ライターム", semanticNet));
        initialLinks.add(new Link("URL", "(株)ワイズ", "https://example.com/株ワイズ", semanticNet));
        initialLinks.add(new Link("URL", "(株)ボードルア【東証グロース上場】", "https://example.com/株ボードルア【東証グロース上場】", semanticNet));
        initialLinks.add(new Link("URL", "ラディックス(株)", "https://example.com/ラディックス株", semanticNet));
        initialLinks.add(new Link("URL", "日鉄ソリューションズ中部(株)【旧社名：(株)NSソリューションズ中部】", "https://example.com/日鉄ソリューションズ中部株【旧社名：株NSソリューションズ中部】", semanticNet));
        initialLinks.add(new Link("URL", "(株)アスパーク", "https://example.com/株アスパーク", semanticNet));
        initialLinks.add(new Link("URL", "(株)北電子", "https://example.com/株北電子", semanticNet));
        initialLinks.add(new Link("URL", "JFEシステムズ(株)【東証スタンダード市場上場】", "https://example.com/JFEシステムズ株【東証スタンダード市場上場】", semanticNet));
        initialLinks.add(new Link("URL", "NRIネットコム(株)【野村総合研究所(NRI)グループ】", "https://example.com/NRIネットコム株【野村総合研究所NRIグループ】", semanticNet));
        initialLinks.add(new Link("URL", "エス・ビー・システムズ(株)【CGCグループ】", "https://example.com/エス・ビー・システムズ株【CGCグループ】", semanticNet));
        initialLinks.add(new Link("URL", "(株)トップ【総合医療機器メーカー】", "https://example.com/株トップ【総合医療機器メーカー】", semanticNet));
        initialLinks.add(new Link("URL", "デンソーテクノ(株)", "https://example.com/デンソーテクノ株", semanticNet));
        initialLinks.add(new Link("URL", "(株)システムインテグレータ【東証スタンダード上場】", "https://example.com/株システムインテグレータ【東証スタンダード上場】", semanticNet));
        initialLinks.add(new Link("URL", "(株)CLIS", "https://example.com/株CLIS", semanticNet));
        initialLinks.add(new Link("URL", "(株)コプロ・ホールディングス（東証プライム・名証プレミア上場）他2社", "https://example.com/株コプロ・ホールディングス（東証プライム・名証プレミア上場）他2社", semanticNet));
        initialLinks.add(new Link("URL", "ウェルネスダイニング(株)", "https://example.com/ウェルネスダイニング株", semanticNet));
        initialLinks.add(new Link("URL", "サティス(株)", "https://example.com/サティス株", semanticNet));
        initialLinks.add(new Link("URL", "萩原電気ホールディングス(株)【東証プライム上場】", "https://example.com/萩原電気ホールディングス株【東証プライム上場】", semanticNet));
        initialLinks.add(new Link("URL", "(株)ランディックス【東証グロース上場】", "https://example.com/株ランディックス【東証グロース上場】", semanticNet));
        initialLinks.add(new Link("URL", "ロジスティードソリューションズ(株)", "https://example.com/ロジスティードソリューションズ株", semanticNet));
        initialLinks.add(new Link("URL", "エイチ・シー・ネットワークス(株)", "https://example.com/エイチ・シー・ネットワークス株", semanticNet));
        initialLinks.add(new Link("URL", "オリエントブレイン(株)", "https://example.com/オリエントブレイン株", semanticNet));
        initialLinks.add(new Link("URL", "(株)ワンエイティ", "https://example.com/株ワンエイティ", semanticNet));
        initialLinks.add(new Link("URL", "あいおいニッセイ同和損害保険(株)", "https://example.com/あいおいニッセイ同和損害保険株", semanticNet));
        initialLinks.add(new Link("URL", "日本軽金属(株)", "https://example.com/日本軽金属株", semanticNet));
        initialLinks.add(new Link("URL", "日本コムシス(株)", "https://example.com/日本コムシス株", semanticNet));
        initialLinks.add(new Link("URL", "(株)野村総合研究所", "https://example.com/株野村総合研究所", semanticNet));
        initialLinks.add(new Link("URL", "(株)NTTデータNJK", "https://example.com/株NTTデータNJK", semanticNet));
        initialLinks.add(new Link("URL", "都築電気(株)【東証プライム市場上場】", "https://example.com/都築電気株【東証プライム市場上場】", semanticNet));
        initialLinks.add(new Link("URL", "兼松エレクトロニクス(株)", "https://example.com/兼松エレクトロニクス株", semanticNet));
        initialLinks.add(new Link("URL", "(株)リンクレア", "https://example.com/株リンクレア", semanticNet));
        initialLinks.add(new Link("URL", "(株)TKC【東証プライム市場上場】", "https://example.com/株TKC【東証プライム市場上場】", semanticNet));
        initialLinks.add(new Link("URL", "(株)東証コンピュータシステム【富士ソフトグループ】", "https://example.com/株東証コンピュータシステム【富士ソフトグループ】", semanticNet));
        initialLinks.add(new Link("URL", "野村ビジネスサービス(株)【野村グループ】", "https://example.com/野村ビジネスサービス株【野村グループ】", semanticNet));
        initialLinks.add(new Link("URL", "ダイハツ工業(株)", "https://example.com/ダイハツ工業株", semanticNet));
        initialLinks.add(new Link("URL", "ソニーグローバルソリューションズ(株)", "https://example.com/ソニーグローバルソリューションズ株", semanticNet));
        initialLinks.add(new Link("URL", "(株)構造計画研究所", "https://example.com/株構造計画研究所", semanticNet));
        initialLinks.add(new Link("URL", "理化工業(株)", "https://example.com/理化工業株", semanticNet));
        initialLinks.add(new Link("URL", "ローツェ(株)【東証プライム市場上場】", "https://example.com/ローツェ株【東証プライム市場上場】", semanticNet));
        initialLinks.add(new Link("URL", "トラスコ中山(株)【東証プライム市場上場】", "https://example.com/トラスコ中山株【東証プライム市場上場】", semanticNet));
        initialLinks.add(new Link("URL", "(株)フォーバル【東証スタンダード上場】", "https://example.com/株フォーバル【東証スタンダード上場】", semanticNet));
        initialLinks.add(new Link("URL", "三谷商事(株)", "https://example.com/三谷商事株", semanticNet));
        initialLinks.add(new Link("URL", "ケミカルグラウト(株)【鹿島グループ】", "https://example.com/ケミカルグラウト株【鹿島グループ】", semanticNet));
        initialLinks.add(new Link("URL", "(株)電通総研【旧社名：(株)電通国際情報サービス（ISID）】", "https://example.com/株電通総研【旧社名：株電通国際情報サービス（ISID）】", semanticNet));
        initialLinks.add(new Link("URL", "横河ブリッジホールディングスグループ", "https://example.com/横河ブリッジホールディングスグループ", semanticNet));
        initialLinks.add(new Link("URL", "(株)前田製作所", "https://example.com/株前田製作所", semanticNet));
        initialLinks.add(new Link("URL", "日鉄日立システムソリューションズ(株)", "https://example.com/日鉄日立システムソリューションズ株", semanticNet));
        initialLinks.add(new Link("URL", "(株)東洋経済新報社", "https://example.com/株東洋経済新報社", semanticNet));
        initialLinks.add(new Link("URL", "豊田通商システムズ(株)(豊田通商グループ)", "https://example.com/豊田通商システムズ株豊田通商グループ", semanticNet));
        initialLinks.add(new Link("URL", "(株)インテリジェント ウェイブ【東証プライム市場上場】", "https://example.com/株インテリジェントウェイブ【東証プライム市場上場】", semanticNet));
        initialLinks.add(new Link("URL", "アサヒビジネスソリューションズ", "https://example.com/アサヒビジネスソリューションズ株【アサヒグループ/CTCグループ】", semanticNet));
        initialLinks.add(new Link("URL", "(株)トラストシステム（ミライトワングループ）", "https://example.com/株トラストシステム（ミライトワングループ）", semanticNet));
        initialLinks.add(new Link("URL", "(株)フェローズ", "https://example.com/株フェローズ", semanticNet));
        initialLinks.add(new Link("URL", "サンワコムシスエンジニアリング(株)【コムシスグループ】", "https://example.com/サンワコムシスエンジニアリング株【コムシスグループ】", semanticNet));
        initialLinks.add(new Link("URL", "デル・テクノロジーズ(株)", "https://example.com/デル・テクノロジーズ株", semanticNet));
        initialLinks.add(new Link("URL", "日本テクノストラクチャア(株)", "https://example.com/日本テクノストラクチャア株", semanticNet));
        initialLinks.add(new Link("URL", "SOMPOダイレクト損害保険(株)", "https://example.com/SOMPOダイレクト損害保険株", semanticNet));
        initialLinks.add(new Link("URL", "JFEプラントエンジ(株)", "https://example.com/JFEプラントエンジ株", semanticNet));
        initialLinks.add(new Link("URL", "(株)All Ads", "https://example.com/株AllAds", semanticNet));
        initialLinks.add(new Link("URL", "(株)エクシオテック", "https://example.com/株エクシオテック", semanticNet));
        initialLinks.add(new Link("URL", "(株)テクノプロジェクト", "https://example.com/株テクノプロジェクト", semanticNet));
        initialLinks.add(new Link("URL", "(株)JSOL（ジェイソル）", "https://example.com/株JSOL（ジェイソル）", semanticNet));
        initialLinks.add(new Link("URL", "中電技術コンサルタント(株)【中国電力グループ】", "https://example.com/中電技術コンサルタント株【中国電力グループ】", semanticNet));
        initialLinks.add(new Link("URL", "(株)ゼウス・エンタープライズ", "https://example.com/株ゼウス・エンタープライズ", semanticNet));
        initialLinks.add(new Link("URL", "光村図書出版(株)", "https://example.com/光村図書出版株", semanticNet));
        initialLinks.add(new Link("URL", "(株)テー・オー・ダブリュー", "https://example.com/株テー・オー・ダブリュー", semanticNet));
        initialLinks.add(new Link("URL", "(株)日経BP", "https://example.com/株日経BP", semanticNet));
        initialLinks.add(new Link("URL", "(株)プライムクロス【野村不動産グループ】", "https://example.com/株プライムクロス【野村不動産グループ】", semanticNet));
        initialLinks.add(new Link("URL", "PayPay銀行(株)【LINEヤフーグループ】", "https://example.com/PayPay銀行株【LINEヤフーグループ】", semanticNet));
        initialLinks.add(new Link("URL", "(株)メディックメディア", "https://example.com/株メディックメディア", semanticNet));
        initialLinks.add(new Link("URL", "(株)S-FIT", "https://example.com/株S-FIT", semanticNet));
        initialLinks.add(new Link("URL", "エムオーテックス(株)", "https://example.com/エムオーテックス株", semanticNet));
        initialLinks.add(new Link("URL", "(株)テレビ朝日サービス", "https://example.com/株テレビ朝日サービス", semanticNet));
        initialLinks.add(new Link("URL", "(株)荒谷建設コンサルタント", "https://example.com/株荒谷建設コンサルタント", semanticNet));
        initialLinks.add(new Link("URL", "(株)立花エレテック【東証プライム上場】", "https://example.com/株立花エレテック【東証プライム上場】", semanticNet));
        initialLinks.add(new Link("URL", "(株)ゲームフリーク", "https://example.com/株ゲームフリーク", semanticNet));
        initialLinks.add(new Link("URL", "(株)Take Action", "https://example.com/株TakeAction", semanticNet));
        initialLinks.add(new Link("URL", "(株)C-mind", "https://example.com/株C-mind", semanticNet));
        initialLinks.add(new Link("URL", "(株)アール・エム", "https://example.com/株アール・エム", semanticNet));
        initialLinks.add(new Link("URL", "ビッグローブ(株)", "https://example.com/ビッグローブ株", semanticNet));
        initialLinks.add(new Link("URL", "(株)システムアイ", "https://example.com/株システムアイ", semanticNet));
        initialLinks.add(new Link("URL", "(株)ダイテック 【DAITEC Co., Ltd.】", "https://example.com/株ダイテック【DAITECCo.,Ltd.】", semanticNet));
        initialLinks.add(new Link("URL", "(株)トップ", "https://example.com/株トップ", semanticNet));
        initialLinks.add(new Link("URL", "(株)SFIDA X", "https://example.com/株SFIDAX", semanticNet));
        initialLinks.add(new Link("URL", "SBペイメントサービス(株)（ソフトバンクグループ）", "https://example.com/SBペイメントサービス株（ソフトバンクグループ）", semanticNet));
        initialLinks.add(new Link("URL", "インフィニオン テクノロジーズ ジャパン(株)", "https://example.com/インフィニオンテクノロジーズジャパン株", semanticNet));
        initialLinks.add(new Link("URL", "(株)三栄建設", "https://example.com/株三栄建設", semanticNet));
        initialLinks.add(new Link("URL", "JBCCグループ", "https://example.com/JBCCグループ", semanticNet));
        initialLinks.add(new Link("URL", "(株)ネクステップ・ソリューションズ", "https://example.com/株ネクステップ・ソリューションズ", semanticNet));
        initialLinks.add(new Link("URL", "パナソニックITS(株)", "https://example.com/パナソニックITS株", semanticNet));
        initialLinks.add(new Link("URL", "グッドモーゲージ(株)【SBIネット銀行ローンプラザ】", "https://example.com/グッドモーゲージ株【SBIネット銀行ローンプラザ】", semanticNet));
        initialLinks.add(new Link("URL", "(株)クオレガ(Cuolega)", "https://example.com/株クオレガCuolega", semanticNet));
        initialLinks.add(new Link("URL", "(株)エナリス【KDDIグループ】", "https://example.com/株エナリス【KDDIグループ】", semanticNet));
        initialLinks.add(new Link("URL", "ワークスデザイン(株)", "https://example.com/ワークスデザイン株", semanticNet));


        // Supplement information\
        initialLinks.add(new Link("supplement", "スターツグループPICK UP", "「出会ったお客様と一生涯のお付き合いをしていきたい」創業以来変わらない想いで多事業展開をしてきた総合生活文化企業のスターツは、今後も地域・社会と共に歩み続けます", semanticNet));
        initialLinks.add(new Link("supplement", "(株)オービックPICK UP", "日本を強くする。", semanticNet));
        initialLinks.add(new Link("supplement", "(株)ミスターマックス・ホールディングス【東証プライム市場上場】", "『原始人も、お殿様も、宇宙人もみんなお客様。』あなたのアイデアが１円を動かし、心を動かすストアマーケティングの世界へ。", semanticNet));
        initialLinks.add(new Link("supplement", "オムロングループ", "「ありたい社会」を、共創しよう　人が活きるオートメーションで、ソーシャルニーズを創造し続ける", semanticNet));
        initialLinks.add(new Link("supplement", "MHI　NSエンジニアリング(株)（三菱重工グループ）", "オンライン説明会エントリー受付中！【三菱重工グループ】地球規模の、仕事をしよう。～原子力プラント、油圧ショベルの開発設計を高度な技術力で支える～", semanticNet));
        initialLinks.add(new Link("supplement", "CTCテクノロジー(株)【CTCT／CTCグループ】", "～IT技術で社会の明日を支える会社～ ／『伊藤忠テクノソリューションズ（CTC）グループ』の中核企業としてITインフラを支えています！", semanticNet));
        initialLinks.add(new Link("supplement", "(株)ライターム", "【IT系】官公庁系・金融系のシステム開発-安定した売上実績!!", semanticNet));
        initialLinks.add(new Link("supplement", "(株)ワイズ", "充実のインセンティブ制度！若手が活躍するオフィス機器の”メーカー兼商社”です！", semanticNet));
        initialLinks.add(new Link("supplement", "(株)ボードルア【東証グロース上場】", "#IT資格取得可#業界理解【謎解き&仕事体験開催】未経験100％/文系8割のITインフラ会社で市場価値を高めよう！", semanticNet));
        initialLinks.add(new Link("supplement", "ラディックス(株)", "＜設立から33年連続で成長している企業＞　企業のお困りごと（業務課題）を解決している仕事です", semanticNet));
        initialLinks.add(new Link("supplement", "日鉄ソリューションズ中部(株)【旧社名：(株)NSソリューションズ中部】", "【日鉄ソリューションズグループ】ともに、その先の答えを ― 中部地区の産業・暮らしを支える地域密着SIer", semanticNet));
        initialLinks.add(new Link("supplement", "(株)アスパーク", "社名の由来でもある【一人ひとりが輝ける会社】を目指している企業です。", semanticNet));
        initialLinks.add(new Link("supplement", "(株)北電子", "新たな時代の幕開け。北電子は”変わらず”、”進化する”!!", semanticNet));
        initialLinks.add(new Link("supplement", "JFEシステムズ(株)【東証スタンダード市場上場】", "【“SIerの上流”を体感】1day仕事体験開催中！/～はたらくをスマートに。はたらく人にスマイルを。～", semanticNet));
        initialLinks.add(new Link("supplement", "NRIネットコム(株)【野村総合研究所(NRI)グループ】", "デジタルの力をたずさえ、お客さまとともに紡いだ「ミライ」の実現に向けた挑戦を続けます。", semanticNet));
        initialLinks.add(new Link("supplement", "エス・ビー・システムズ(株)【CGCグループ】", "大手スーパーに後れを取らない競争力をつけて頂くために。全国のCGCグループ中堅中小スーパーマーケットを支援するシステムを提供します。【転勤なし】【ESなし】", semanticNet));
        initialLinks.add(new Link("supplement", "(株)トップ【総合医療機器メーカー】", "患者様にも医療従事者様にも安全な”真にやさしい”医療の実現を目指して【創業84年/長期連続成長/社員を大切にする経営/シェアNo.1製品多数/自社一貫生産/ボーナス年3回】", semanticNet));
        initialLinks.add(new Link("supplement", "デンソーテクノ(株)", "設計したい。その希望に応える会社。", semanticNet));
        initialLinks.add(new Link("supplement", "(株)システムインテグレータ【東証スタンダード上場】", "自社パッケージ・クラウドを武器に成長を続けている東証スタンダード上場企業。社員育成が企業力と考え社員教育を徹底していますので、高度なスキルを身に付けられます。", semanticNet));
        initialLinks.add(new Link("supplement", "(株)CLIS", "CLISは、プルデンシャル・グループと日本IBMが共同出資する『戦略的システム・インテグレータ』です。", semanticNet));
        initialLinks.add(new Link("supplement", "(株)コプロ・ホールディングス（東証プライム・名証プレミア上場）他2社", "「建設業界で、唯一無二の存在」を目指して、『人』との出会いを大切にする会社です。", semanticNet));
        initialLinks.add(new Link("supplement", "ウェルネスダイニング(株)", "食事制限に特化した健康宅配食事業のリーディングカンパニー「からだ想い、家族想いのあったか健康応援団」", semanticNet));
        initialLinks.add(new Link("supplement", "サティス(株)", "変革するデジタルインダストリーをリード挑戦・信頼・成長・平等・持続のコアバリューに基づくテクノロジーでイノベーションを実現する会社", semanticNet));
        initialLinks.add(new Link("supplement", "萩原電気ホールディングス(株)【東証プライム上場】", "商社×メーカーの機能を併せ持ち、自動車業界を中心とした多くのモノづくりを支えています。", semanticNet));
        initialLinks.add(new Link("supplement", "(株)ランディックス【東証グロース上場】", "【上場ベンチャー | 安定×成長】若手が挑戦し活躍する組織・圧倒的成長スピードが速い", semanticNet));
        initialLinks.add(new Link("supplement", "ロジスティードソリューションズ(株)", "ロジスティクスIT企業グローバルNo.１へ！「物流をもっとよくする」物流特化型ソフトウェア開発～システム提案まで一貫したソリューションを提供しています。", semanticNet));
        initialLinks.add(new Link("supplement", "エイチ・シー・ネットワークス(株)", "◆エイチ・シー・ネットワークスは、ＳＩｅｒ×メーカーの強みで社会全体を広く深く支えています。◆年間休日126日。借上げ寮制度など充実の福利厚生制度が自慢！", semanticNet));
        initialLinks.add(new Link("supplement", "オリエントブレイン(株)", "映像情報・光センサーを柔軟に活用し産業現場に貢献【江坂駅から徒歩1分＆年間休日120日以上＆完全週休二日制＆転勤なし＆社宅・家賃補助制度あり】", semanticNet));
        initialLinks.add(new Link("supplement", "(株)ワンエイティ", "現状維持じゃつまらない。180°視点を変えて、ワクワクできる取り組みを。", semanticNet));
        initialLinks.add(new Link("supplement", "あいおいニッセイ同和損害保険(株)", "未来に、奮えたことはあるか。", semanticNet));
        initialLinks.add(new Link("supplement", "日本軽金属(株)", "チーム日軽金として異次元の素材メーカーへ", semanticNet));
        initialLinks.add(new Link("supplement", "日本コムシス(株)", "【日経225　コムシスグループ中核企業】インフラ×ICTで、この国のみらいの街づくりを担う企業", semanticNet));
        initialLinks.add(new Link("supplement", "(株)野村総合研究所", "変化を楽しみ、変化を起こす。", semanticNet));
        initialLinks.add(new Link("supplement", "(株)NTTデータNJK", "持てる力を、今、未来へ/Now Ready", semanticNet));
        initialLinks.add(new Link("supplement", "都築電気(株)【東証プライム市場上場】", "「ICT」という言葉すら存在しない時代に誕生した、歴史と技術を誇るSierです。", semanticNet));
        initialLinks.add(new Link("supplement", "兼松エレクトロニクス(株)", "【可能性キミシダイ】兼松グループの商社系SIer", semanticNet));
        initialLinks.add(new Link("supplement", "(株)リンクレア", "～デジタルで社会にもっとワクワクを～　設立55周年を迎える独立系IT企業", semanticNet));
        initialLinks.add(new Link("supplement", "(株)TKC【東証プライム市場上場】", "ITで社会を支える縁の下の力持ち！税理士や公務員等の専門家向けのシステム開発に特化。会計事務所や自治体向けソフトウェア業界における高いシェア。万全な教育体制。", semanticNet));
        initialLinks.add(new Link("supplement", "(株)東証コンピュータシステム【富士ソフトグループ】", "東京証券取引所のシステムを60年以上支えた技術と経験で、金融業界をはじめとするあらゆる需要に合わせたサービスを提供", semanticNet));
        initialLinks.add(new Link("supplement", "野村ビジネスサービス(株)【野村グループ】", "野村グループのハブとしてビジネスを繋いでいます。オペレーションを核に証券・人事業務から他分野に業容拡大中！", semanticNet));
        initialLinks.add(new Link("supplement", "ダイハツ工業(株)", "Light you up　～キミが走れば、セカイが輝く。～", semanticNet));
        initialLinks.add(new Link("supplement", "ソニーグローバルソリューションズ(株)", "【デジタル×ソニー×IS】世界で通用するデジタル変革者として活躍してほしい", semanticNet));
        initialLinks.add(new Link("supplement", "(株)構造計画研究所", "さまざまな知識や経験を融合させて新しい『解』を作りだす。学問と社会がつながっていくダイナミックな『場』があります。", semanticNet));
        initialLinks.add(new Link("supplement", "理化工業(株)", "【国内シェアNo.1】【賞与昨年実績17カ月】【昨年度休日125日】半導体、自動車、食品、医療など、モノ作りからサービスまで高度な温度制御技術で支えます。", semanticNet));
        initialLinks.add(new Link("supplement", "ローツェ(株)【東証プライム市場上場】", "世の中にないものをつくるローツェ。世界No.1を目指す技術集団です。", semanticNet));
        initialLinks.add(new Link("supplement", "トラスコ中山(株)【東証プライム市場上場】", "「がんばれ!!日本のモノづくり」トラスコ中山は日本のモノづくり企業をプロツールの流通を通して支えている専門商社です！！", semanticNet));
        initialLinks.add(new Link("supplement", "(株)フォーバル【東証スタンダード上場】", "「新しいあたりまえ」で、新しい世界を創る (5期連続最高益/年間休日120日以上/DX認定企業/福利厚生推進法人/年齢関係なく実績とプロセスに応じた評価制度/配属地確約)", semanticNet));
        initialLinks.add(new Link("supplement", "三谷商事(株)", "建設・エネルギー・ITを中心に、その他様々な事業を展開する独立系商社。新しい発想と行動力のある、「出る杭」となる人材が活躍中です。", semanticNet));
        initialLinks.add(new Link("supplement", "ケミカルグラウト(株)【鹿島グループ】", "60年以上無借金黒字経営！地下技術のパイオニア【鹿島建設Gr・福利厚生充実・年間休日125日超・完全週休二日制・防災減災・液状化対策・建築基礎・土壌浄化・環境対策】", semanticNet));
        initialLinks.add(new Link("supplement", "(株)電通総研【旧社名：(株)電通国際情報サービス（ISID）】", "HUMANOLOGY for the future 人とテクノロジーで、その先をつくる。", semanticNet));
        initialLinks.add(new Link("supplement", "横河ブリッジホールディングスグループ", "【つなぐ、むすぶ、ひろげる、未来へ】社会インフラの整備に力を注ぐ「技術の横河」、その視線は次の100年へ", semanticNet));
        initialLinks.add(new Link("supplement", "(株)前田製作所", "「かにクレーン」をはじめとするユニークな自社商品の開発製造、「コマツ」の総販売代理店など、建設機械業界において幅広いビジネスを展開しています", semanticNet));
        initialLinks.add(new Link("supplement", "日鉄日立システムソリューションズ(株)", "新日本製鐵(株)（現 日本製鉄(株)）と(株)日立製作所。2つの大手企業の高いノウハウを受け継ぎ、成長してきたSI企業。", semanticNet));
        initialLinks.add(new Link("supplement", "(株)東洋経済新報社", "いつの時代も客観的なデータに基づく確かな情報を、雑誌・書籍・インターネット等、様々な媒体で配信。多くのビジネスパーソンの「考えるヒント」であり続けています。", semanticNet));
        initialLinks.add(new Link("supplement", "豊田通商システムズ(株)(豊田通商グループ)", "【IT×グローバル】システムインテグレーターとIT商社の強みを発揮し、トヨタグループの発展にグローバルに貢献！", semanticNet));
        initialLinks.add(new Link("supplement", "(株)インテリジェント ウェイブ【東証プライム市場上場】", "～高速・安全・高品質なIT基盤開発に強み～ 自社製品のカード決済/不正検知システムは国内シェアNo.1！", semanticNet));
        initialLinks.add(new Link("supplement", "アサヒビジネスソリューションズ", "私たちはアサヒグループ各社のＩＴ戦略を実現する情報サービス会社です。", semanticNet));
        initialLinks.add(new Link("supplement", "(株)トラストシステム（ミライトワングループ）", "ミライトワングループの安定した会社！社員を大切にする会社です。証券・金融・通信・その他の幅広い業務スキルが身に付きます！", semanticNet));
        initialLinks.add(new Link("supplement", "(株)フェローズ", "クリエイティブ業界専門の人材サービスです！", semanticNet));
        initialLinks.add(new Link("supplement", "サンワコムシスエンジニアリング(株)【コムシスグループ】", "情報通信、電気設備の総合エンジニアリング企業として、スマート社会の未来に貢献します", semanticNet));
        initialLinks.add(new Link("supplement", "デル・テクノロジーズ(株)", "企業や人々がもっと豊かになるために、暮らしや社会の変革を支援する総合ITソリューション・ベンダー", semanticNet));
        initialLinks.add(new Link("supplement", "日本テクノストラクチャア(株)", "多彩なシステムソリューションで、未来の社会インフラづくりに貢献しています！", semanticNet));
        initialLinks.add(new Link("supplement", "SOMPOダイレクト損害保険(株)", "～飽くなき創造　生み出す価値～「業界初」のヒット商品を創出。急成長中のダイレクト通販損害保険会社！", semanticNet));
        initialLinks.add(new Link("supplement", "JFEプラントエンジ(株)", "製鉄業を中心に様々な業界、官公庁に向け事業を展開するプラントエンジニアリング企業", semanticNet));
        initialLinks.add(new Link("supplement", "(株)All Ads", "次世代型マーケティングを推進し、「嫌いなスマホ広告を好きな広告になる未来」を創る", semanticNet));
        initialLinks.add(new Link("supplement", "(株)エクシオテック", "高い技術力でスマート革命をサポートし、変革と挑戦により前進し続けるICT総合エンジニアリング企業です！", semanticNet));
        initialLinks.add(new Link("supplement", "(株)テクノプロジェクト", "生きるを良くする技術欲。", semanticNet));
        initialLinks.add(new Link("supplement", "(株)JSOL（ジェイソル）", "今はない、答えを創る。", semanticNet));
        initialLinks.add(new Link("supplement", "中電技術コンサルタント(株)【中国電力グループ】", "多様化、複合化する社会資本整備に貢献し、安全で快適な社会の創造に向けて挑戦を続ける総合建設コンサルタント。", semanticNet));
        initialLinks.add(new Link("supplement", "(株)ゼウス・エンタープライズ", "『終身雇用を掲げるIT企業』社会のあたりまえを支える仕事＃ネットワークセキュリティ＃教育に強い＃文理不問＃首都圏勤務＃転勤なし", semanticNet));
        initialLinks.add(new Link("supplement", "光村図書出版(株)", "子どもたちの豊かな未来のために　本物を探して75年", semanticNet));
        initialLinks.add(new Link("supplement", "(株)テー・オー・ダブリュー", "新しい時代の体験を創る", semanticNet));
        initialLinks.add(new Link("supplement", "(株)日経BP", "多彩な専門性で読者・顧客・社会にその先を示す", semanticNet));
        initialLinks.add(new Link("supplement", "(株)プライムクロス【野村不動産グループ】", "野村不動産×セプテーニHD。WEB広告代理・サイト制作・マーケティング事業などワンストップでソリューションを提供するデジタルマーケティングカンパニー。", semanticNet));
        initialLinks.add(new Link("supplement", "PayPay銀行(株)【LINEヤフーグループ】", "PayPay銀行は「ネットやスマホアプリ」で今までにない「お得・便利」をお客さまへ提供する「ネット銀行」です。", semanticNet));
        initialLinks.add(new Link("supplement", "(株)メディックメディア", "医学書総合ランキングTOP15に6冊ランクイン！医学教育で圧倒的シェア！書籍・映像・アプリ…あらゆる手段で、「専門的な医学知識を わかりやすく より多くの人へ」", semanticNet));
        initialLinks.add(new Link("supplement", "(株)S-FIT", "【ベンチャー部門トップ独走】時代の変革者集団が『SPECIAL ONE』で輝く！", semanticNet));
        initialLinks.add(new Link("supplement", "エムオーテックス(株)", "【京セラグループ】文理問わず活躍中！11月1日より冬インターンシップ受付開始！（セミナー画面より申し込み可）", semanticNet));
        initialLinks.add(new Link("supplement", "(株)テレビ朝日サービス", "私たちテレビ朝日サービスは、テレビ朝日グループをはじめ、放送・映像業界を支える、幅広い事業を展開しています。", semanticNet));
        initialLinks.add(new Link("supplement", "(株)荒谷建設コンサルタント", "Be Araise! ―次世代に誇れる価値共創企業へ― 創業から108年。中四国の地域の暮らしを守り、地域から信頼され続ける企業を目指しています。", semanticNet));
        initialLinks.add(new Link("supplement", "(株)立花エレテック【東証プライム上場】", "＼創業103年 技術商社のリーディングカンパニー／社員の4分の1が技術者！/“開発力”と“提案力”が強み！/DXプロジェクト推進中/女性のキャリアアップも支援", semanticNet));
        initialLinks.add(new Link("supplement", "(株)ゲームフリーク", "まだ見ぬ驚きと笑顔をつくろう。~Bringing smiles and new surprises to the world~", semanticNet));
        initialLinks.add(new Link("supplement", "(株)Take Action", "《働く人に熱を。組織にエネルギーを。》- 大人が真剣に夢を語る、そんな社会をつくる - 人材×IT×コンサルティングカンパニー", semanticNet));
        initialLinks.add(new Link("supplement", "(株)C-mind", "＼創業から12期連続で増収中／IT・人材・不動産業界にイノベーションを。", semanticNet));
        initialLinks.add(new Link("supplement", "(株)アール・エム", "3年後の課長たちへ！自己成長こそが、将来の安定！2026年までに業界No.1を目指す――", semanticNet));
        initialLinks.add(new Link("supplement", "ビッグローブ(株)", "屋内での快適なインターネット利用のための光接続から、格安SIM・スマホまでさまざまな接続サービスを提供する企業です。", semanticNet));
        initialLinks.add(new Link("supplement", "(株)システムアイ", "《交通費・宿泊費支給のITキャリアセミナー実施》キャリアコンサルタントと共に、エンジニアキャリアを考えてみませんか？◆文系大歓迎◆書類選考なし◆希望者は面接確約", semanticNet));
        initialLinks.add(new Link("supplement", "(株)ダイテック 【DAITEC Co., Ltd.】", "国内トップクラスのシェア！自社開発ソフトで高収益のIT企業！", semanticNet));
        initialLinks.add(new Link("supplement", "(株)トップ", "【安定企業×成長環境】社会人をスタート#総合商社#全国42拠点 #土日祝休み 【成果】をきっちり評価！昇格と給与へスピード還元■入社後は【新人研修カリキュラム】を用意", semanticNet));
        initialLinks.add(new Link("supplement", "(株)SFIDA X", "【挑戦】と【成長】を続けるベンチャー企業。Webコンサルティングを中心として幅広いビジネスを展開しています！", semanticNet));
        initialLinks.add(new Link("supplement", "SBペイメントサービス(株)（ソフトバンクグループ）", "キャッシュレス時代のリーディングカンパニーへ", semanticNet));
        initialLinks.add(new Link("supplement", "インフィニオン テクノロジーズ ジャパン(株)", "Driving decarbonization and digitalization. Together.インフィニオンは車載半導体とパワー半導体で世界1位のシェアを誇る半導体メーカーです。", semanticNet));
        initialLinks.add(new Link("supplement", "(株)三栄建設", "【大阪をつくっていく】3Dモデリング× 鉄骨製作事業｜施工管理 × 総合建設事業｜2つの事業で大阪のランドマークに携わります！", semanticNet));
        initialLinks.add(new Link("supplement", "JBCCグループ", "速い、だから差がつく。柔軟、だから変われる。", semanticNet));
        initialLinks.add(new Link("supplement", "(株)ネクステップ・ソリューションズ", "独自の事業拡大・業務効率化ソリューションする元請けSIer。「自由」のもとに「個」のポテンシャルが光る社会を実現！", semanticNet));
        initialLinks.add(new Link("supplement", "パナソニックITS(株)", "パナソニックグループ唯一の車載製品に特化した設計開発のエンジニアリング会社です", semanticNet));
        initialLinks.add(new Link("supplement", "グッドモーゲージ(株)【SBIネット銀行ローンプラザ】", "『ネット』と『リアル』の融合！住信SBIネット銀行専属銀行代理業者第1号！", semanticNet));
        initialLinks.add(new Link("supplement", "(株)クオレガ(Cuolega)", "★成長×社会貢献★「IT」を駆使して「食」「宿泊」業界に特化した人材コンサルティングを行う会社！住宅手当やバースデーシップなどベンチャーながらも充実した福利厚生！", semanticNet));
        initialLinks.add(new Link("supplement", "(株)エナリス【KDDIグループ】", "（東京）脱炭素社会の実現に取り組むエネルギーの総合ソリューション企業/ITのチカラで再生可能エネルギーの普及を図り、効率的にエネルギーを活用できる社会を目指す。", semanticNet));
        initialLinks.add(new Link("supplement", "ワークスデザイン(株)", "“新たな価値を描く”コンサルティング会社！仲間と「楽しく、笑い、少しふざけあい」＃リモートOK＃WEBマーケ＃経営コンサルティング", semanticNet));

        // Picturepath information
        initialLinks.add(new Link("picturePath", "スターツグループPICK UP", "/スターツグループPICKUP.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)オービックPICK UP", "/株オービックPICKUP.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)ミスターマックス・ホールディングス【東証プライム市場上場】", "/株ミスターマックス・ホールディングス【東証プライム市場上場】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "オムロングループ", "/オムロングループ.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "MHI　NSエンジニアリング(株)（三菱重工グループ）", "/MHI　NSエンジニアリング株（三菱重工グループ）.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "CTCテクノロジー(株)【CTCT／CTCグループ】", "/CTCテクノロジー株【CTCT／CTCグループ】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)ライターム", "/株ライターム.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)ワイズ", "/株ワイズ.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)ボードルア【東証グロース上場】", "/株ボードルア【東証グロース上場】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "ラディックス(株)", "/ラディックス株.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "日鉄ソリューションズ中部(株)【旧社名：(株)NSソリューションズ中部】", "/日鉄ソリューションズ中部株【旧社名：株NSソリューションズ中部】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)アスパーク", "/株アスパーク.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)北電子", "/株北電子.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "JFEシステムズ(株)【東証スタンダード市場上場】", "/JFEシステムズ株【東証スタンダード市場上場】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "NRIネットコム(株)【野村総合研究所(NRI)グループ】", "/NRIネットコム株【野村総合研究所NRIグループ】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "エス・ビー・システムズ(株)【CGCグループ】", "/エス・ビー・システムズ株【CGCグループ】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)トップ【総合医療機器メーカー】", "/株トップ【総合医療機器メーカー】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "デンソーテクノ(株)", "/デンソーテクノ株.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)システムインテグレータ【東証スタンダード上場】", "/株システムインテグレータ【東証スタンダード上場】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)CLIS", "/株CLIS.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)コプロ・ホールディングス（東証プライム・名証プレミア上場）他2社", "/株コプロ・ホールディングス（東証プライム・名証プレミア上場）他2社.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "ウェルネスダイニング(株)", "/ウェルネスダイニング株.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "サティス(株)", "/サティス株.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "萩原電気ホールディングス(株)【東証プライム上場】", "/萩原電気ホールディングス株【東証プライム上場】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)ランディックス【東証グロース上場】", "/株ランディックス【東証グロース上場】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "ロジスティードソリューションズ(株)", "/ロジスティードソリューションズ株.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "エイチ・シー・ネットワークス(株)", "/エイチ・シー・ネットワークス株.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "オリエントブレイン(株)", "/オリエントブレイン株.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)ワンエイティ", "/株ワンエイティ.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "あいおいニッセイ同和損害保険(株)", "/あいおいニッセイ同和損害保険株.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "日本軽金属(株)", "/日本軽金属株.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "日本コムシス(株)", "/日本コムシス株.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)野村総合研究所", "/株野村総合研究所.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)NTTデータNJK", "/株NTTデータNJK.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "都築電気(株)【東証プライム市場上場】", "/都築電気株【東証プライム市場上場】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "兼松エレクトロニクス(株)", "/兼松エレクトロニクス株.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)リンクレア", "/株リンクレア.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)TKC【東証プライム市場上場】", "/株TKC【東証プライム市場上場】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)東証コンピュータシステム【富士ソフトグループ】", "/株東証コンピュータシステム【富士ソフトグループ】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "野村ビジネスサービス(株)【野村グループ】", "/野村ビジネスサービス株【野村グループ】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "ダイハツ工業(株)", "/ダイハツ工業株.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "ソニーグローバルソリューションズ(株)", "/ソニーグローバルソリューションズ株.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)構造計画研究所", "/株構造計画研究所.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "理化工業(株)", "/理化工業株.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "ローツェ(株)【東証プライム市場上場】", "/ローツェ株【東証プライム市場上場】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "トラスコ中山(株)【東証プライム市場上場】", "/トラスコ中山株【東証プライム市場上場】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)フォーバル【東証スタンダード上場】", "/株フォーバル【東証スタンダード上場】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "三谷商事(株)", "/三谷商事株.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "ケミカルグラウト(株)【鹿島グループ】", "/ケミカルグラウト株【鹿島グループ】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)電通総研【旧社名：(株)電通国際情報サービス（ISID）】", "/株電通総研【旧社名：株電通国際情報サービス（ISID）】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "横河ブリッジホールディングスグループ", "/横河ブリッジホールディングスグループ.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)前田製作所", "/株前田製作所.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "日鉄日立システムソリューションズ(株)", "/日鉄日立システムソリューションズ株.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)東洋経済新報社", "/株東洋経済新報社.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "豊田通商システムズ(株)(豊田通商グループ)", "/豊田通商システムズ株豊田通商グループ.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)インテリジェント ウェイブ【東証プライム市場上場】", "/株インテリジェントウェイブ【東証プライム市場上場】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "アサヒビジネスソリューションズ", "/アサヒビジネスソリューションズ株【アサヒグループ/CTCグループ】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)トラストシステム（ミライトワングループ）", "/株トラストシステム（ミライトワングループ）.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)フェローズ", "/株フェローズ.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "サンワコムシスエンジニアリング(株)【コムシスグループ】", "/サンワコムシスエンジニアリング株【コムシスグループ】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "デル・テクノロジーズ(株)", "/デル・テクノロジーズ株.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "日本テクノストラクチャア(株)", "/日本テクノストラクチャア株.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "SOMPOダイレクト損害保険(株)", "/SOMPOダイレクト損害保険株.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "JFEプラントエンジ(株)", "/JFEプラントエンジ株.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)All Ads", "/株AllAds.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)エクシオテック", "/株エクシオテック.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)テクノプロジェクト", "/株テクノプロジェクト.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)JSOL（ジェイソル）", "/株JSOL（ジェイソル）.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "中電技術コンサルタント(株)【中国電力グループ】", "/中電技術コンサルタント株【中国電力グループ】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)ゼウス・エンタープライズ", "/株ゼウス・エンタープライズ.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "光村図書出版(株)", "/光村図書出版株.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)テー・オー・ダブリュー", "/株テー・オー・ダブリュー.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)日経BP", "/株日経BP.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)プライムクロス【野村不動産グループ】", "/株プライムクロス【野村不動産グループ】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "PayPay銀行(株)【LINEヤフーグループ】", "/PayPay銀行株【LINEヤフーグループ】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)メディックメディア", "/株メディックメディア.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)S-FIT", "/株S-FIT.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "エムオーテックス(株)", "/エムオーテックス株.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)テレビ朝日サービス", "/株テレビ朝日サービス.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)荒谷建設コンサルタント", "/株荒谷建設コンサルタント.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)立花エレテック【東証プライム上場】", "/株立花エレテック【東証プライム上場】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)ゲームフリーク", "/株ゲームフリーク.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)Take Action", "/株TakeAction.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)C-mind", "/株C-mind.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)アール・エム", "/株アール・エム.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "ビッグローブ(株)", "/ビッグローブ株.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)システムアイ", "/株システムアイ.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)ダイテック 【DAITEC Co., Ltd.】", "/株ダイテック【DAITECCo.,Ltd.】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)トップ", "/株トップ.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)SFIDA X", "/株SFIDAX.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "SBペイメントサービス(株)（ソフトバンクグループ）", "/SBペイメントサービス株（ソフトバンクグループ）.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "インフィニオン テクノロジーズ ジャパン(株)", "/インフィニオンテクノロジーズジャパン株.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)三栄建設", "/株三栄建設.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "JBCCグループ", "/JBCCグループ.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)ネクステップ・ソリューションズ", "/株ネクステップ・ソリューションズ.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "パナソニックITS(株)", "/パナソニックITS株.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "グッドモーゲージ(株)【SBIネット銀行ローンプラザ】", "/グッドモーゲージ株【SBIネット銀行ローンプラザ】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)クオレガ(Cuolega)", "/株クオレガCuolega.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "(株)エナリス【KDDIグループ】", "/株エナリス【KDDIグループ】.jpg", semanticNet));
        initialLinks.add(new Link("picturePath", "ワークスデザイン(株)", "/ワークスデザイン株.jpg", semanticNet));


        for (Link link : initialLinks) {
            semanticNet.addLink(link);
        }
    }
}
